"""Tier 2 ReferenceChart entries for Fujifilm lenses.

Generated by `tools/mtfdigitizer/scripts/scaffold_fuji_tier2.py`.
Plot boxes auto-detected by `fuji_plotbox.detect_fuji_plotbox`.
Do not hand-edit; re-run the scaffolder to update.

At time of generation: 60 lenses, 193 chart images.
"""

from __future__ import annotations

from .charts import ChartView, PlotBoxCoords, ReferenceChart


FUJI_TIER2_CHARTS: tuple[ReferenceChart, ...] = (
    ReferenceChart(
        slug="fujifilm-gf-100-200mm-f5-6-r-lm-ois-wr",
        chart_path="docs/optical-specs/fujifilm-gf-100-200mm-f5-6-r-lm-ois-wr/fujifilm-gf-100-200mm-f5-6-r-lm-ois-wr-tele-10lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(10, 20, 40),
        image_height_mm=26.9,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the GF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=15, x_right=250, y_top=4, y_bottom=186),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-100-200mm-f5-6-r-lm-ois-wr/fujifilm-gf-100-200mm-f5-6-r-lm-ois-wr-tele-20lp.png",
                plot_box=PlotBoxCoords(x_left=15, x_right=250, y_top=4, y_bottom=186),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-100-200mm-f5-6-r-lm-ois-wr/fujifilm-gf-100-200mm-f5-6-r-lm-ois-wr-tele-40lp.png",
                plot_box=PlotBoxCoords(x_left=15, x_right=250, y_top=4, y_bottom=187),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-100-200mm-f5-6-r-lm-ois-wr/fujifilm-gf-100-200mm-f5-6-r-lm-ois-wr-wide-10lp.png",
                plot_box=PlotBoxCoords(x_left=15, x_right=250, y_top=0, y_bottom=186),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-100-200mm-f5-6-r-lm-ois-wr/fujifilm-gf-100-200mm-f5-6-r-lm-ois-wr-wide-20lp.png",
                plot_box=PlotBoxCoords(x_left=15, x_right=250, y_top=4, y_bottom=186),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-100-200mm-f5-6-r-lm-ois-wr/fujifilm-gf-100-200mm-f5-6-r-lm-ois-wr-wide-40lp.png",
                plot_box=PlotBoxCoords(x_left=16, x_right=251, y_top=4, y_bottom=187),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-gf-110mm-f2-0-r-lm-wr",
        chart_path="docs/optical-specs/fujifilm-gf-110mm-f2-0-r-lm-wr/fujifilm-gf-110mm-f2-0-r-lm-wr-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 20, 40),
        image_height_mm=26.9,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the GF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=19, x_right=246, y_top=0, y_bottom=185),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-110mm-f2-0-r-lm-wr/fujifilm-gf-110mm-f2-0-r-lm-wr-20lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=244, y_top=4, y_bottom=185),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-110mm-f2-0-r-lm-wr/fujifilm-gf-110mm-f2-0-r-lm-wr-40lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=244, y_top=4, y_bottom=185),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-gf-110mm-f5-6-ts-macro",
        chart_path="docs/optical-specs/fujifilm-gf-110mm-f5-6-ts-macro/fujifilm-gf-110mm-f5-6-ts-macro-10lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(10, 20, 40),
        image_height_mm=26.9,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the GF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=23, x_right=411, y_top=0, y_bottom=285),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-110mm-f5-6-ts-macro/fujifilm-gf-110mm-f5-6-ts-macro-20lp.png",
                plot_box=PlotBoxCoords(x_left=25, x_right=410, y_top=17, y_bottom=284),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-110mm-f5-6-ts-macro/fujifilm-gf-110mm-f5-6-ts-macro-40lp.png",
                plot_box=PlotBoxCoords(x_left=25, x_right=410, y_top=17, y_bottom=283),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-gf-120mm-f4-r-lm-ois-wr-macro",
        chart_path="docs/optical-specs/fujifilm-gf-120mm-f4-r-lm-ois-wr-macro/fujifilm-gf-120mm-f4-r-lm-ois-wr-macro-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 20, 40),
        image_height_mm=26.9,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the GF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=22, x_right=248, y_top=0, y_bottom=185),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-120mm-f4-r-lm-ois-wr-macro/fujifilm-gf-120mm-f4-r-lm-ois-wr-macro-20lp.png",
                plot_box=PlotBoxCoords(x_left=19, x_right=245, y_top=4, y_bottom=185),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-120mm-f4-r-lm-ois-wr-macro/fujifilm-gf-120mm-f4-r-lm-ois-wr-macro-40lp.png",
                plot_box=PlotBoxCoords(x_left=21, x_right=247, y_top=4, y_bottom=185),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-gf-20-35mm-f4-r-wr",
        chart_path="docs/optical-specs/fujifilm-gf-20-35mm-f4-r-wr/fujifilm-gf-20-35mm-f4-r-wr-tele-10lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(10, 20, 40),
        image_height_mm=26.9,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the GF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=19, x_right=336, y_top=19, y_bottom=239),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-20-35mm-f4-r-wr/fujifilm-gf-20-35mm-f4-r-wr-tele-20lp.png",
                plot_box=PlotBoxCoords(x_left=18, x_right=335, y_top=18, y_bottom=238),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-20-35mm-f4-r-wr/fujifilm-gf-20-35mm-f4-r-wr-tele-40lp.png",
                plot_box=PlotBoxCoords(x_left=19, x_right=335, y_top=18, y_bottom=238),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-20-35mm-f4-r-wr/fujifilm-gf-20-35mm-f4-r-wr-wide-10lp.png",
                plot_box=PlotBoxCoords(x_left=19, x_right=338, y_top=21, y_bottom=240),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-20-35mm-f4-r-wr/fujifilm-gf-20-35mm-f4-r-wr-wide-20lp.png",
                plot_box=PlotBoxCoords(x_left=18, x_right=337, y_top=0, y_bottom=239),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-20-35mm-f4-r-wr/fujifilm-gf-20-35mm-f4-r-wr-wide-40lp.png",
                plot_box=PlotBoxCoords(x_left=19, x_right=336, y_top=0, y_bottom=238),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-gf-250mm-f4-r-lm-ois-wr",
        chart_path="docs/optical-specs/fujifilm-gf-250mm-f4-r-lm-ois-wr/fujifilm-gf-250mm-f4-r-lm-ois-wr-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 20, 40),
        image_height_mm=26.9,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the GF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=19, x_right=246, y_top=4, y_bottom=188),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-250mm-f4-r-lm-ois-wr/fujifilm-gf-250mm-f4-r-lm-ois-wr-20lp.png",
                plot_box=PlotBoxCoords(x_left=19, x_right=246, y_top=4, y_bottom=188),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-250mm-f4-r-lm-ois-wr/fujifilm-gf-250mm-f4-r-lm-ois-wr-40lp.png",
                plot_box=PlotBoxCoords(x_left=19, x_right=246, y_top=4, y_bottom=188),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-gf-30mm-f3-5-r-wr",
        chart_path="docs/optical-specs/fujifilm-gf-30mm-f3-5-r-wr/fujifilm-gf-30mm-f3-5-r-wr-10lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(10, 20, 40),
        image_height_mm=26.9,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the GF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=42, x_right=270, y_top=4, y_bottom=185),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-30mm-f3-5-r-wr/fujifilm-gf-30mm-f3-5-r-wr-20lp.png",
                plot_box=PlotBoxCoords(x_left=43, x_right=271, y_top=4, y_bottom=185),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-30mm-f3-5-r-wr/fujifilm-gf-30mm-f3-5-r-wr-40lp.png",
                plot_box=PlotBoxCoords(x_left=38, x_right=270, y_top=142, y_bottom=184),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-gf-30mm-f5-6-ts",
        chart_path="docs/optical-specs/fujifilm-gf-30mm-f5-6-ts/fujifilm-gf-30mm-f5-6-ts-10lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(10, 20, 40),
        image_height_mm=26.9,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the GF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=23, x_right=411, y_top=16, y_bottom=283),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-30mm-f5-6-ts/fujifilm-gf-30mm-f5-6-ts-20lp.png",
                plot_box=PlotBoxCoords(x_left=25, x_right=410, y_top=16, y_bottom=283),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-30mm-f5-6-ts/fujifilm-gf-30mm-f5-6-ts-40lp.png",
                plot_box=PlotBoxCoords(x_left=25, x_right=410, y_top=16, y_bottom=282),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-gf-32-64mm-f4-r-lm-wr",
        chart_path="docs/optical-specs/fujifilm-gf-32-64mm-f4-r-lm-wr/fujifilm-gf-32-64mm-f4-r-lm-wr-tele-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 20, 45),
        image_height_mm=26.9,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the GF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=19, x_right=250, y_top=4, y_bottom=186),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-32-64mm-f4-r-lm-wr/fujifilm-gf-32-64mm-f4-r-lm-wr-tele-20lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=248, y_top=4, y_bottom=186),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-32-64mm-f4-r-lm-wr/fujifilm-gf-32-64mm-f4-r-lm-wr-tele-45lp.png",
                plot_box=PlotBoxCoords(x_left=19, x_right=250, y_top=4, y_bottom=186),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-32-64mm-f4-r-lm-wr/fujifilm-gf-32-64mm-f4-r-lm-wr-wide-15lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=248, y_top=0, y_bottom=186),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-32-64mm-f4-r-lm-wr/fujifilm-gf-32-64mm-f4-r-lm-wr-wide-20lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=248, y_top=0, y_bottom=186),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-32-64mm-f4-r-lm-wr/fujifilm-gf-32-64mm-f4-r-lm-wr-wide-45lp.png",
                plot_box=PlotBoxCoords(x_left=19, x_right=250, y_top=4, y_bottom=186),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-gf-35-70mm-f4-5-5-6-wr",
        chart_path="docs/optical-specs/fujifilm-gf-35-70mm-f4-5-5-6-wr/fujifilm-gf-35-70mm-f4-5-5-6-wr-tele-10lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(10, 20, 40),
        image_height_mm=26.9,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the GF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=23, x_right=321, y_top=42, y_bottom=246),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-35-70mm-f4-5-5-6-wr/fujifilm-gf-35-70mm-f4-5-5-6-wr-tele-20lp.png",
                plot_box=PlotBoxCoords(x_left=23, x_right=321, y_top=42, y_bottom=246),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-35-70mm-f4-5-5-6-wr/fujifilm-gf-35-70mm-f4-5-5-6-wr-tele-40lp.png",
                plot_box=PlotBoxCoords(x_left=23, x_right=321, y_top=42, y_bottom=246),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-35-70mm-f4-5-5-6-wr/fujifilm-gf-35-70mm-f4-5-5-6-wr-wide-10lp.png",
                plot_box=PlotBoxCoords(x_left=23, x_right=321, y_top=42, y_bottom=246),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-35-70mm-f4-5-5-6-wr/fujifilm-gf-35-70mm-f4-5-5-6-wr-wide-20lp.png",
                plot_box=PlotBoxCoords(x_left=23, x_right=321, y_top=42, y_bottom=246),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-35-70mm-f4-5-5-6-wr/fujifilm-gf-35-70mm-f4-5-5-6-wr-wide-40lp.png",
                plot_box=PlotBoxCoords(x_left=23, x_right=321, y_top=42, y_bottom=246),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-gf-45-100mm-f4-r-lm-ois-wr",
        chart_path="docs/optical-specs/fujifilm-gf-45-100mm-f4-r-lm-ois-wr/fujifilm-gf-45-100mm-f4-r-lm-ois-wr-tele-10lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(10, 20, 40),
        image_height_mm=26.9,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the GF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=38, x_right=705, y_top=10, y_bottom=522),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-45-100mm-f4-r-lm-ois-wr/fujifilm-gf-45-100mm-f4-r-lm-ois-wr-tele-20lp.png",
                plot_box=PlotBoxCoords(x_left=38, x_right=705, y_top=10, y_bottom=522),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-45-100mm-f4-r-lm-ois-wr/fujifilm-gf-45-100mm-f4-r-lm-ois-wr-tele-40lp.png",
                plot_box=PlotBoxCoords(x_left=38, x_right=705, y_top=10, y_bottom=522),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-45-100mm-f4-r-lm-ois-wr/fujifilm-gf-45-100mm-f4-r-lm-ois-wr-wide-10lp.png",
                plot_box=PlotBoxCoords(x_left=40, x_right=705, y_top=13, y_bottom=523),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-45-100mm-f4-r-lm-ois-wr/fujifilm-gf-45-100mm-f4-r-lm-ois-wr-wide-20lp.png",
                plot_box=PlotBoxCoords(x_left=38, x_right=705, y_top=10, y_bottom=522),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-45-100mm-f4-r-lm-ois-wr/fujifilm-gf-45-100mm-f4-r-lm-ois-wr-wide-40lp.png",
                plot_box=PlotBoxCoords(x_left=40, x_right=705, y_top=12, y_bottom=522),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-gf-45mm-f2-8-r-wr",
        chart_path="docs/optical-specs/fujifilm-gf-45mm-f2-8-r-wr/fujifilm-gf-45mm-f2-8-r-wr-10lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(10, 20, 40),
        image_height_mm=26.9,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the GF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=22, x_right=242, y_top=0, y_bottom=179),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-45mm-f2-8-r-wr/fujifilm-gf-45mm-f2-8-r-wr-20lp.png",
                plot_box=PlotBoxCoords(x_left=23, x_right=243, y_top=4, y_bottom=179),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-45mm-f2-8-r-wr/fujifilm-gf-45mm-f2-8-r-wr-40lp.png",
                plot_box=PlotBoxCoords(x_left=26, x_right=246, y_top=4, y_bottom=179),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-gf-500mm-f5-6-r-lm-ois-wr",
        chart_path="docs/optical-specs/fujifilm-gf-500mm-f5-6-r-lm-ois-wr/fujifilm-gf-500mm-f5-6-r-lm-ois-wr-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 20, 40),
        image_height_mm=26.9,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the GF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=15, x_right=252, y_top=0, y_bottom=182),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-500mm-f5-6-r-lm-ois-wr/fujifilm-gf-500mm-f5-6-r-lm-ois-wr-20lp.png",
                plot_box=PlotBoxCoords(x_left=15, x_right=250, y_top=0, y_bottom=180),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-500mm-f5-6-r-lm-ois-wr/fujifilm-gf-500mm-f5-6-r-lm-ois-wr-40lp.png",
                plot_box=PlotBoxCoords(x_left=15, x_right=251, y_top=20, y_bottom=180),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-gf-50mm-f3-5-r-lm-wr",
        chart_path="docs/optical-specs/fujifilm-gf-50mm-f3-5-r-lm-wr/fujifilm-gf-50mm-f3-5-r-lm-wr-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 20, 45),
        image_height_mm=26.9,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the GF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=32, x_right=581, y_top=4, y_bottom=432),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-50mm-f3-5-r-lm-wr/fujifilm-gf-50mm-f3-5-r-lm-wr-20lp.png",
                plot_box=PlotBoxCoords(x_left=33, x_right=581, y_top=4, y_bottom=431),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-50mm-f3-5-r-lm-wr/fujifilm-gf-50mm-f3-5-r-lm-wr-45lp.png",
                plot_box=PlotBoxCoords(x_left=32, x_right=581, y_top=4, y_bottom=432),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-gf-55mm-f1-7-r-wr",
        chart_path="docs/optical-specs/fujifilm-gf-55mm-f1-7-r-wr/fujifilm-gf-55mm-f1-7-r-wr-10lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(10, 20, 40),
        image_height_mm=26.9,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the GF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=19, x_right=338, y_top=14, y_bottom=233),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-55mm-f1-7-r-wr/fujifilm-gf-55mm-f1-7-r-wr-20lp.png",
                plot_box=PlotBoxCoords(x_left=18, x_right=337, y_top=13, y_bottom=232),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-55mm-f1-7-r-wr/fujifilm-gf-55mm-f1-7-r-wr-40lp.png",
                plot_box=PlotBoxCoords(x_left=19, x_right=336, y_top=56, y_bottom=231),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-gf-63mm-f2-8-r-wr",
        chart_path="docs/optical-specs/fujifilm-gf-63mm-f2-8-r-wr/fujifilm-gf-63mm-f2-8-r-wr-10lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(10, 20, 45),
        image_height_mm=26.9,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the GF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=18, x_right=249, y_top=4, y_bottom=183),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-63mm-f2-8-r-wr/fujifilm-gf-63mm-f2-8-r-wr-20lp.png",
                plot_box=PlotBoxCoords(x_left=15, x_right=247, y_top=4, y_bottom=183),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-63mm-f2-8-r-wr/fujifilm-gf-63mm-f2-8-r-wr-45lp.png",
                plot_box=PlotBoxCoords(x_left=18, x_right=249, y_top=4, y_bottom=183),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-gf-80mm-f1-7-r-wr",
        chart_path="docs/optical-specs/fujifilm-gf-80mm-f1-7-r-wr/fujifilm-gf-80mm-f1-7-r-wr-10lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(10, 20, 40),
        image_height_mm=26.9,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the GF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=17, x_right=240, y_top=0, y_bottom=184),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-80mm-f1-7-r-wr/fujifilm-gf-80mm-f1-7-r-wr-20lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=240, y_top=0, y_bottom=184),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-gf-80mm-f1-7-r-wr/fujifilm-gf-80mm-f1-7-r-wr-40lp.png",
                plot_box=PlotBoxCoords(x_left=16, x_right=241, y_top=99, y_bottom=184),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xc-13-33mm-f3-5-6-3-ois",
        chart_path="docs/optical-specs/fujifilm-xc-13-33mm-f3-5-6-3-ois/fujifilm-xc-13-33mm-f3-5-6-3-ois-tele-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XC mount default."
        ),
        plot_box=PlotBoxCoords(x_left=28, x_right=239, y_top=12, y_bottom=182),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xc-13-33mm-f3-5-6-3-ois/fujifilm-xc-13-33mm-f3-5-6-3-ois-tele-45lp.png",
                plot_box=PlotBoxCoords(x_left=28, x_right=239, y_top=12, y_bottom=182),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xc-13-33mm-f3-5-6-3-ois/fujifilm-xc-13-33mm-f3-5-6-3-ois-wide-15lp.png",
                plot_box=PlotBoxCoords(x_left=28, x_right=239, y_top=12, y_bottom=182),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xc-13-33mm-f3-5-6-3-ois/fujifilm-xc-13-33mm-f3-5-6-3-ois-wide-45lp.png",
                plot_box=PlotBoxCoords(x_left=28, x_right=239, y_top=12, y_bottom=182),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xc-35mm-f2-0",
        chart_path="docs/optical-specs/fujifilm-xc-35mm-f2-0/fujifilm-xc-35mm-f2-0-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XC mount default."
        ),
        plot_box=PlotBoxCoords(x_left=16, x_right=234, y_top=4, y_bottom=181),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xc-35mm-f2-0/fujifilm-xc-35mm-f2-0-45lp.png",
                plot_box=PlotBoxCoords(x_left=16, x_right=234, y_top=4, y_bottom=181),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xc-50-230mm-f4-5-6-7-ois-ii",
        chart_path="docs/optical-specs/fujifilm-xc-50-230mm-f4-5-6-7-ois-ii/fujifilm-xc-50-230mm-f4-5-6-7-ois-ii-tele-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XC mount default."
        ),
        plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=0, y_bottom=184),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xc-50-230mm-f4-5-6-7-ois-ii/fujifilm-xc-50-230mm-f4-5-6-7-ois-ii-tele-45lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=4, y_bottom=184),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xc-50-230mm-f4-5-6-7-ois-ii/fujifilm-xc-50-230mm-f4-5-6-7-ois-ii-wide-15lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=4, y_bottom=184),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xc-50-230mm-f4-5-6-7-ois-ii/fujifilm-xc-50-230mm-f4-5-6-7-ois-ii-wide-45lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=4, y_bottom=184),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-10-24mm-f4-r-ois",
        chart_path="docs/optical-specs/fujifilm-xf-10-24mm-f4-r-ois/fujifilm-xf-10-24mm-f4-r-ois-tele-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=4, y_bottom=184),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-10-24mm-f4-r-ois/fujifilm-xf-10-24mm-f4-r-ois-tele-45lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=4, y_bottom=184),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-10-24mm-f4-r-ois/fujifilm-xf-10-24mm-f4-r-ois-wide-15lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=4, y_bottom=184),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-10-24mm-f4-r-ois/fujifilm-xf-10-24mm-f4-r-ois-wide-45lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=4, y_bottom=184),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-10-24mm-f4-r-ois-wr",
        chart_path="docs/optical-specs/fujifilm-xf-10-24mm-f4-r-ois-wr/fujifilm-xf-10-24mm-f4-r-ois-wr-tele-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=4, y_bottom=184),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-10-24mm-f4-r-ois-wr/fujifilm-xf-10-24mm-f4-r-ois-wr-tele-45lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=4, y_bottom=184),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-10-24mm-f4-r-ois-wr/fujifilm-xf-10-24mm-f4-r-ois-wr-wide-15lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=4, y_bottom=184),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-10-24mm-f4-r-ois-wr/fujifilm-xf-10-24mm-f4-r-ois-wr-wide-45lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=4, y_bottom=184),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-100-400mm-f4-5-5-6-r-lm-ois-wr",
        chart_path="docs/optical-specs/fujifilm-xf-100-400mm-f4-5-5-6-r-lm-ois-wr/fujifilm-xf-100-400mm-f4-5-5-6-r-lm-ois-wr-tele-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=13, x_right=233, y_top=4, y_bottom=181),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-100-400mm-f4-5-5-6-r-lm-ois-wr/fujifilm-xf-100-400mm-f4-5-5-6-r-lm-ois-wr-tele-45lp.png",
                plot_box=PlotBoxCoords(x_left=14, x_right=234, y_top=4, y_bottom=186),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-100-400mm-f4-5-5-6-r-lm-ois-wr/fujifilm-xf-100-400mm-f4-5-5-6-r-lm-ois-wr-wide-15lp.png",
                plot_box=PlotBoxCoords(x_left=13, x_right=233, y_top=4, y_bottom=180),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-100-400mm-f4-5-5-6-r-lm-ois-wr/fujifilm-xf-100-400mm-f4-5-5-6-r-lm-ois-wr-wide-45lp.png",
                plot_box=PlotBoxCoords(x_left=13, x_right=233, y_top=4, y_bottom=181),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-14mm-f2-8-r",
        chart_path="docs/optical-specs/fujifilm-xf-14mm-f2-8-r/fujifilm-xf-14mm-f2-8-r-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=0, y_bottom=184),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-14mm-f2-8-r/fujifilm-xf-14mm-f2-8-r-45lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=0, y_bottom=184),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-150-600mm-f5-6-8-r-lm-ois-wr",
        chart_path="docs/optical-specs/fujifilm-xf-150-600mm-f5-6-8-r-lm-ois-wr/fujifilm-xf-150-600mm-f5-6-8-r-lm-ois-wr-tele-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=17, x_right=341, y_top=30, y_bottom=249),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-150-600mm-f5-6-8-r-lm-ois-wr/fujifilm-xf-150-600mm-f5-6-8-r-lm-ois-wr-tele-45lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=340, y_top=30, y_bottom=249),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-150-600mm-f5-6-8-r-lm-ois-wr/fujifilm-xf-150-600mm-f5-6-8-r-lm-ois-wr-wide-15lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=341, y_top=30, y_bottom=251),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-150-600mm-f5-6-8-r-lm-ois-wr/fujifilm-xf-150-600mm-f5-6-8-r-lm-ois-wr-wide-45lp.png",
                plot_box=PlotBoxCoords(x_left=18, x_right=340, y_top=72, y_bottom=249),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-16-50mm-f2-8-4-8-r-lm-wr",
        chart_path="docs/optical-specs/fujifilm-xf-16-50mm-f2-8-4-8-r-lm-wr/fujifilm-xf-16-50mm-f2-8-4-8-r-lm-wr-tele-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=21, x_right=243, y_top=0, y_bottom=187),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-16-50mm-f2-8-4-8-r-lm-wr/fujifilm-xf-16-50mm-f2-8-4-8-r-lm-wr-tele-45lp.png",
                plot_box=PlotBoxCoords(x_left=21, x_right=243, y_top=78, y_bottom=187),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-16-50mm-f2-8-4-8-r-lm-wr/fujifilm-xf-16-50mm-f2-8-4-8-r-lm-wr-wide-15lp.png",
                plot_box=PlotBoxCoords(x_left=21, x_right=243, y_top=0, y_bottom=187),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-16-50mm-f2-8-4-8-r-lm-wr/fujifilm-xf-16-50mm-f2-8-4-8-r-lm-wr-wide-45lp.png",
                plot_box=PlotBoxCoords(x_left=21, x_right=243, y_top=78, y_bottom=187),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-16-55mm-f2-8-r-lm-wr",
        chart_path="docs/optical-specs/fujifilm-xf-16-55mm-f2-8-r-lm-wr/fujifilm-xf-16-55mm-f2-8-r-lm-wr-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=16, x_right=232, y_top=4, y_bottom=181),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-16-55mm-f2-8-r-lm-wr/fujifilm-xf-16-55mm-f2-8-r-lm-wr-45lp.png",
                plot_box=PlotBoxCoords(x_left=16, x_right=233, y_top=4, y_bottom=181),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-16-55mm-f2-8-r-lm-wr/fujifilm-xf-16-55mm-f2-8-r-lm-wr-tele-15lp.png",
                plot_box=PlotBoxCoords(x_left=15, x_right=231, y_top=4, y_bottom=185),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-16-55mm-f2-8-r-lm-wr/fujifilm-xf-16-55mm-f2-8-r-lm-wr-tele-45lp.png",
                plot_box=PlotBoxCoords(x_left=15, x_right=232, y_top=4, y_bottom=185),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-16-55mm-f2-8-r-lm-wr/fujifilm-xf-16-55mm-f2-8-r-lm-wr-wide-15lp.png",
                plot_box=PlotBoxCoords(x_left=16, x_right=232, y_top=4, y_bottom=181),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-16-55mm-f2-8-r-lm-wr/fujifilm-xf-16-55mm-f2-8-r-lm-wr-wide-45lp.png",
                plot_box=PlotBoxCoords(x_left=16, x_right=233, y_top=4, y_bottom=181),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-16-55mm-f2-8-r-lm-wr-ii",
        chart_path="docs/optical-specs/fujifilm-xf-16-55mm-f2-8-r-lm-wr-ii/fujifilm-xf-16-55mm-f2-8-r-lm-wr-ii-45lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=28, x_right=239, y_top=4, y_bottom=184),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-16-55mm-f2-8-r-lm-wr-ii/fujifilm-xf-16-55mm-f2-8-r-lm-wr-ii-tele-15lp.png",
                plot_box=PlotBoxCoords(x_left=28, x_right=239, y_top=4, y_bottom=184),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-16-55mm-f2-8-r-lm-wr-ii/fujifilm-xf-16-55mm-f2-8-r-lm-wr-ii-tele-45lp.png",
                plot_box=PlotBoxCoords(x_left=28, x_right=239, y_top=4, y_bottom=184),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-16-55mm-f2-8-r-lm-wr-ii/fujifilm-xf-16-55mm-f2-8-r-lm-wr-ii-wide-15lp.png",
                plot_box=PlotBoxCoords(x_left=28, x_right=239, y_top=4, y_bottom=184),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-16-55mm-f2-8-r-lm-wr-ii/fujifilm-xf-16-55mm-f2-8-r-lm-wr-ii-wide-45lp.png",
                plot_box=PlotBoxCoords(x_left=28, x_right=239, y_top=4, y_bottom=184),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-16-80mm-f4-r-ois-wr",
        chart_path="docs/optical-specs/fujifilm-xf-16-80mm-f4-r-ois-wr/fujifilm-xf-16-80mm-f4-r-ois-wr-tele-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=34, x_right=640, y_top=102, y_bottom=475),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-16-80mm-f4-r-ois-wr/fujifilm-xf-16-80mm-f4-r-ois-wr-tele-45lp.png",
                plot_box=PlotBoxCoords(x_left=34, x_right=641, y_top=102, y_bottom=474),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-16-80mm-f4-r-ois-wr/fujifilm-xf-16-80mm-f4-r-ois-wr-wide-15lp.png",
                plot_box=PlotBoxCoords(x_left=34, x_right=640, y_top=102, y_bottom=475),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-16-80mm-f4-r-ois-wr/fujifilm-xf-16-80mm-f4-r-ois-wr-wide-45lp.png",
                plot_box=PlotBoxCoords(x_left=34, x_right=641, y_top=102, y_bottom=474),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-16mm-f1-4-r-wr",
        chart_path="docs/optical-specs/fujifilm-xf-16mm-f1-4-r-wr/fujifilm-xf-16mm-f1-4-r-wr-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=12, x_right=234, y_top=4, y_bottom=182),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-16mm-f1-4-r-wr/fujifilm-xf-16mm-f1-4-r-wr-45lp.png",
                plot_box=PlotBoxCoords(x_left=12, x_right=234, y_top=4, y_bottom=182),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-16mm-f2-8-r-wr",
        chart_path="docs/optical-specs/fujifilm-xf-16mm-f2-8-r-wr/fujifilm-xf-16mm-f2-8-r-wr-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=15, x_right=233, y_top=4, y_bottom=184),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-16mm-f2-8-r-wr/fujifilm-xf-16mm-f2-8-r-wr-45lp.png",
                plot_box=PlotBoxCoords(x_left=15, x_right=233, y_top=4, y_bottom=183),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-18-120mm-f4-lm-pz-wr",
        chart_path="docs/optical-specs/fujifilm-xf-18-120mm-f4-lm-pz-wr/fujifilm-xf-18-120mm-f4-lm-pz-wr-tele-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=17, x_right=342, y_top=30, y_bottom=261),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-18-120mm-f4-lm-pz-wr/fujifilm-xf-18-120mm-f4-lm-pz-wr-tele-45lp.png",
                plot_box=PlotBoxCoords(x_left=18, x_right=342, y_top=30, y_bottom=261),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-18-120mm-f4-lm-pz-wr/fujifilm-xf-18-120mm-f4-lm-pz-wr-wide-15lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=342, y_top=30, y_bottom=262),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-18-120mm-f4-lm-pz-wr/fujifilm-xf-18-120mm-f4-lm-pz-wr-wide-45lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=342, y_top=30, y_bottom=260),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-18-135mm-f3-5-5-6-r-lm-ois-wr",
        chart_path="docs/optical-specs/fujifilm-xf-18-135mm-f3-5-5-6-r-lm-ois-wr/fujifilm-xf-18-135mm-f3-5-5-6-r-lm-ois-wr-tele-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=4, y_bottom=184),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-18-135mm-f3-5-5-6-r-lm-ois-wr/fujifilm-xf-18-135mm-f3-5-5-6-r-lm-ois-wr-tele-45lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=4, y_bottom=184),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-18-135mm-f3-5-5-6-r-lm-ois-wr/fujifilm-xf-18-135mm-f3-5-5-6-r-lm-ois-wr-wide-15lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=4, y_bottom=184),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-18-135mm-f3-5-5-6-r-lm-ois-wr/fujifilm-xf-18-135mm-f3-5-5-6-r-lm-ois-wr-wide-45lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=4, y_bottom=184),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-18-55mm-f2-8-4-0-r-lm-ois",
        chart_path="docs/optical-specs/fujifilm-xf-18-55mm-f2-8-4-0-r-lm-ois/fujifilm-xf-18-55mm-f2-8-4-0-r-lm-ois-tele-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=17, x_right=234, y_top=4, y_bottom=184),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-18-55mm-f2-8-4-0-r-lm-ois/fujifilm-xf-18-55mm-f2-8-4-0-r-lm-ois-tele-45lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=234, y_top=4, y_bottom=184),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-18-55mm-f2-8-4-0-r-lm-ois/fujifilm-xf-18-55mm-f2-8-4-0-r-lm-ois-wide-15lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=234, y_top=4, y_bottom=184),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-18-55mm-f2-8-4-0-r-lm-ois/fujifilm-xf-18-55mm-f2-8-4-0-r-lm-ois-wide-45lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=234, y_top=4, y_bottom=184),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-18mm-f1-4-r-lm-wr",
        chart_path="docs/optical-specs/fujifilm-xf-18mm-f1-4-r-lm-wr/fujifilm-xf-18mm-f1-4-r-lm-wr-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=22, x_right=306, y_top=17, y_bottom=246),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-18mm-f1-4-r-lm-wr/fujifilm-xf-18mm-f1-4-r-lm-wr-45lp.png",
                plot_box=PlotBoxCoords(x_left=23, x_right=306, y_top=0, y_bottom=246),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-18mm-f2-0-r",
        chart_path="docs/optical-specs/fujifilm-xf-18mm-f2-0-r/fujifilm-xf-18mm-f2-0-r-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=15, x_right=232, y_top=0, y_bottom=183),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-18mm-f2-0-r/fujifilm-xf-18mm-f2-0-r-45lp.png",
                plot_box=PlotBoxCoords(x_left=15, x_right=232, y_top=0, y_bottom=183),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-200mm-f2-0-r-lm-ois-wr",
        chart_path="docs/optical-specs/fujifilm-xf-200mm-f2-0-r-lm-ois-wr/fujifilm-xf-200mm-f2-0-r-lm-ois-wr-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=17, x_right=231, y_top=0, y_bottom=182),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-200mm-f2-0-r-lm-ois-wr/fujifilm-xf-200mm-f2-0-r-lm-ois-wr-45lp.png",
                plot_box=PlotBoxCoords(x_left=18, x_right=231, y_top=4, y_bottom=183),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-23mm-f1-4-r",
        chart_path="docs/optical-specs/fujifilm-xf-23mm-f1-4-r/fujifilm-xf-23mm-f1-4-r-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=2, y_bottom=184),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-23mm-f1-4-r/fujifilm-xf-23mm-f1-4-r-45lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=4, y_bottom=184),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-23mm-f2-0-r-wr",
        chart_path="docs/optical-specs/fujifilm-xf-23mm-f2-0-r-wr/fujifilm-xf-23mm-f2-0-r-wr-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=16, x_right=232, y_top=4, y_bottom=179),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-23mm-f2-0-r-wr/fujifilm-xf-23mm-f2-0-r-wr-45lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=233, y_top=4, y_bottom=180),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-23mm-f2-8-r-wr",
        chart_path="docs/optical-specs/fujifilm-xf-23mm-f2-8-r-wr/fujifilm-xf-23mm-f2-8-r-wr-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=80, x_right=808, y_top=155, y_bottom=630),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-23mm-f2-8-r-wr/fujifilm-xf-23mm-f2-8-r-wr-45lp.png",
                plot_box=PlotBoxCoords(x_left=71, x_right=795, y_top=160, y_bottom=624),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-27mm-f2-8-r",
        chart_path="docs/optical-specs/fujifilm-xf-27mm-f2-8-r/fujifilm-xf-27mm-f2-8-r-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=4, y_bottom=184),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-27mm-f2-8-r/fujifilm-xf-27mm-f2-8-r-45lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=4, y_bottom=184),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-27mm-f2-8-r-wr",
        chart_path="docs/optical-specs/fujifilm-xf-27mm-f2-8-r-wr/fujifilm-xf-27mm-f2-8-r-wr-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=4, y_bottom=184),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-27mm-f2-8-r-wr/fujifilm-xf-27mm-f2-8-r-wr-45lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=4, y_bottom=184),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-30mm-f2-8-r-lm-wr-macro",
        chart_path="docs/optical-specs/fujifilm-xf-30mm-f2-8-r-lm-wr-macro/fujifilm-xf-30mm-f2-8-r-lm-wr-macro-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=28, x_right=326, y_top=0, y_bottom=247),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-30mm-f2-8-r-lm-wr-macro/fujifilm-xf-30mm-f2-8-r-lm-wr-macro-45lp.png",
                plot_box=PlotBoxCoords(x_left=28, x_right=326, y_top=0, y_bottom=247),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-33mm-f1-4-r-lm-wr",
        chart_path="docs/optical-specs/fujifilm-xf-33mm-f1-4-r-lm-wr/fujifilm-xf-33mm-f1-4-r-lm-wr-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=19, x_right=319, y_top=0, y_bottom=246),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-33mm-f1-4-r-lm-wr/fujifilm-xf-33mm-f1-4-r-lm-wr-45lp.png",
                plot_box=PlotBoxCoords(x_left=19, x_right=320, y_top=0, y_bottom=247),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-35mm-f1-4-r",
        chart_path="docs/optical-specs/fujifilm-xf-35mm-f1-4-r/fujifilm-xf-35mm-f1-4-r-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=15, x_right=232, y_top=0, y_bottom=183),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-35mm-f1-4-r/fujifilm-xf-35mm-f1-4-r-45lp.png",
                plot_box=PlotBoxCoords(x_left=15, x_right=232, y_top=0, y_bottom=183),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-35mm-f2-0-r-wr",
        chart_path="docs/optical-specs/fujifilm-xf-35mm-f2-0-r-wr/fujifilm-xf-35mm-f2-0-r-wr-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=16, x_right=234, y_top=4, y_bottom=181),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-35mm-f2-0-r-wr/fujifilm-xf-35mm-f2-0-r-wr-45lp.png",
                plot_box=PlotBoxCoords(x_left=15, x_right=253, y_top=4, y_bottom=181),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-50-140mm-f2-8-r-lm-ois-wr",
        chart_path="docs/optical-specs/fujifilm-xf-50-140mm-f2-8-r-lm-ois-wr/fujifilm-xf-50-140mm-f2-8-r-lm-ois-wr-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=4, y_bottom=184),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-50-140mm-f2-8-r-lm-ois-wr/fujifilm-xf-50-140mm-f2-8-r-lm-ois-wr-45lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=4, y_bottom=184),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-50-140mm-f2-8-r-lm-ois-wr/fujifilm-xf-50-140mm-f2-8-r-lm-ois-wr-tele-15lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=0, y_bottom=184),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-50-140mm-f2-8-r-lm-ois-wr/fujifilm-xf-50-140mm-f2-8-r-lm-ois-wr-tele-45lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=4, y_bottom=184),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-50-140mm-f2-8-r-lm-ois-wr/fujifilm-xf-50-140mm-f2-8-r-lm-ois-wr-wide-15lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=4, y_bottom=184),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-50-140mm-f2-8-r-lm-ois-wr/fujifilm-xf-50-140mm-f2-8-r-lm-ois-wr-wide-45lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=4, y_bottom=184),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-500mm-f5-6-r-lm-ois-wr",
        chart_path="docs/optical-specs/fujifilm-xf-500mm-f5-6-r-lm-ois-wr/fujifilm-xf-500mm-f5-6-r-lm-ois-wr-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=28, x_right=240, y_top=0, y_bottom=184),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-500mm-f5-6-r-lm-ois-wr/fujifilm-xf-500mm-f5-6-r-lm-ois-wr-45lp.png",
                plot_box=PlotBoxCoords(x_left=28, x_right=241, y_top=0, y_bottom=183),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-50mm-f1-0-r-wr",
        chart_path="docs/optical-specs/fujifilm-xf-50mm-f1-0-r-wr/fujifilm-xf-50mm-f1-0-r-wr-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=19, x_right=312, y_top=0, y_bottom=246),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-50mm-f1-0-r-wr/fujifilm-xf-50mm-f1-0-r-wr-45lp.png",
                plot_box=PlotBoxCoords(x_left=18, x_right=312, y_top=0, y_bottom=246),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-50mm-f2-0-r-wr",
        chart_path="docs/optical-specs/fujifilm-xf-50mm-f2-0-r-wr/fujifilm-xf-50mm-f2-0-r-wr-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=15, x_right=233, y_top=4, y_bottom=182),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-50mm-f2-0-r-wr/fujifilm-xf-50mm-f2-0-r-wr-45lp.png",
                plot_box=PlotBoxCoords(x_left=15, x_right=233, y_top=4, y_bottom=183),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-55-200mm-f3-5-4-8-r-lm-ois",
        chart_path="docs/optical-specs/fujifilm-xf-55-200mm-f3-5-4-8-r-lm-ois/fujifilm-xf-55-200mm-f3-5-4-8-r-lm-ois-tele-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=0, y_bottom=184),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-55-200mm-f3-5-4-8-r-lm-ois/fujifilm-xf-55-200mm-f3-5-4-8-r-lm-ois-tele-45lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=4, y_bottom=184),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-55-200mm-f3-5-4-8-r-lm-ois/fujifilm-xf-55-200mm-f3-5-4-8-r-lm-ois-wide-15lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=0, y_bottom=184),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-55-200mm-f3-5-4-8-r-lm-ois/fujifilm-xf-55-200mm-f3-5-4-8-r-lm-ois-wide-45lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=4, y_bottom=184),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-56mm-f1-2-r",
        chart_path="docs/optical-specs/fujifilm-xf-56mm-f1-2-r/fujifilm-xf-56mm-f1-2-r-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=18, x_right=231, y_top=4, y_bottom=185),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-56mm-f1-2-r/fujifilm-xf-56mm-f1-2-r-45lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=230, y_top=4, y_bottom=185),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-56mm-f1-2-r-apd",
        chart_path="docs/optical-specs/fujifilm-xf-56mm-f1-2-r-apd/fujifilm-xf-56mm-f1-2-r-apd-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=4, y_bottom=184),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-56mm-f1-2-r-apd/fujifilm-xf-56mm-f1-2-r-apd-45lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=232, y_top=4, y_bottom=184),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-56mm-f1-2-r-wr",
        chart_path="docs/optical-specs/fujifilm-xf-56mm-f1-2-r-wr/fujifilm-xf-56mm-f1-2-r-wr-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=22, x_right=337, y_top=0, y_bottom=249),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-56mm-f1-2-r-wr/fujifilm-xf-56mm-f1-2-r-wr-45lp.png",
                plot_box=PlotBoxCoords(x_left=22, x_right=337, y_top=35, y_bottom=249),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-60mm-f2-4-r-macro",
        chart_path="docs/optical-specs/fujifilm-xf-60mm-f2-4-r-macro/fujifilm-xf-60mm-f2-4-r-macro-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=15, x_right=232, y_top=0, y_bottom=183),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-60mm-f2-4-r-macro/fujifilm-xf-60mm-f2-4-r-macro-45lp.png",
                plot_box=PlotBoxCoords(x_left=15, x_right=232, y_top=0, y_bottom=183),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-70-300mm-f4-5-6-r-lm-ois-wr",
        chart_path="docs/optical-specs/fujifilm-xf-70-300mm-f4-5-6-r-lm-ois-wr/fujifilm-xf-70-300mm-f4-5-6-r-lm-ois-wr-tele-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=23, x_right=307, y_top=0, y_bottom=247),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-70-300mm-f4-5-6-r-lm-ois-wr/fujifilm-xf-70-300mm-f4-5-6-r-lm-ois-wr-tele-45lp.png",
                plot_box=PlotBoxCoords(x_left=23, x_right=306, y_top=0, y_bottom=247),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-70-300mm-f4-5-6-r-lm-ois-wr/fujifilm-xf-70-300mm-f4-5-6-r-lm-ois-wr-wide-15lp.png",
                plot_box=PlotBoxCoords(x_left=23, x_right=307, y_top=16, y_bottom=247),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-70-300mm-f4-5-6-r-lm-ois-wr/fujifilm-xf-70-300mm-f4-5-6-r-lm-ois-wr-wide-45lp.png",
                plot_box=PlotBoxCoords(x_left=22, x_right=306, y_top=16, y_bottom=247),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-8-16mm-f2-8-r-lm-wr",
        chart_path="docs/optical-specs/fujifilm-xf-8-16mm-f2-8-r-lm-wr/fujifilm-xf-8-16mm-f2-8-r-lm-wr-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=13, x_right=234, y_top=0, y_bottom=182),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-8-16mm-f2-8-r-lm-wr/fujifilm-xf-8-16mm-f2-8-r-lm-wr-45lp.png",
                plot_box=PlotBoxCoords(x_left=13, x_right=234, y_top=4, y_bottom=182),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-8-16mm-f2-8-r-lm-wr/fujifilm-xf-8-16mm-f2-8-r-lm-wr-tele-15lp.png",
                plot_box=PlotBoxCoords(x_left=13, x_right=234, y_top=4, y_bottom=184),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-8-16mm-f2-8-r-lm-wr/fujifilm-xf-8-16mm-f2-8-r-lm-wr-tele-45lp.png",
                plot_box=PlotBoxCoords(x_left=13, x_right=234, y_top=4, y_bottom=184),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-8-16mm-f2-8-r-lm-wr/fujifilm-xf-8-16mm-f2-8-r-lm-wr-wide-15lp.png",
                plot_box=PlotBoxCoords(x_left=13, x_right=234, y_top=0, y_bottom=182),
            ),
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-8-16mm-f2-8-r-lm-wr/fujifilm-xf-8-16mm-f2-8-r-lm-wr-wide-45lp.png",
                plot_box=PlotBoxCoords(x_left=13, x_right=234, y_top=4, y_bottom=182),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-80mm-f2-8-r-lm-ois-wr-macro",
        chart_path="docs/optical-specs/fujifilm-xf-80mm-f2-8-r-lm-ois-wr-macro/fujifilm-xf-80mm-f2-8-r-lm-ois-wr-macro-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=15, x_right=232, y_top=4, y_bottom=183),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-80mm-f2-8-r-lm-ois-wr-macro/fujifilm-xf-80mm-f2-8-r-lm-ois-wr-macro-45lp.png",
                plot_box=PlotBoxCoords(x_left=17, x_right=234, y_top=4, y_bottom=182),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-8mm-f3-5-r-wr",
        chart_path="docs/optical-specs/fujifilm-xf-8mm-f3-5-r-wr/fujifilm-xf-8mm-f3-5-r-wr-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=19, x_right=335, y_top=108, y_bottom=260),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-8mm-f3-5-r-wr/fujifilm-xf-8mm-f3-5-r-wr-45lp.png",
                plot_box=PlotBoxCoords(x_left=19, x_right=335, y_top=108, y_bottom=261),
            ),
        ),
    ),
    ReferenceChart(
        slug="fujifilm-xf-90mm-f2-0-r-lm-wr",
        chart_path="docs/optical-specs/fujifilm-xf-90mm-f2-0-r-lm-wr/fujifilm-xf-90mm-f2-0-r-lm-wr-15lp.png",
        style_family="fujifilm-permfreq",
        apertures=("max",),
        frequencies_lpmm=(15, 45),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041) scaffolded by `scaffold_fuji_tier2`; plot box auto-detected by `fuji_plotbox.detect_fuji_plotbox`. Per-image image_height_mm is constant within a lens; calibration via the XF mount default."
        ),
        plot_box=PlotBoxCoords(x_left=14, x_right=234, y_top=0, y_bottom=181),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/fujifilm-xf-90mm-f2-0-r-lm-wr/fujifilm-xf-90mm-f2-0-r-lm-wr-45lp.png",
                plot_box=PlotBoxCoords(x_left=13, x_right=233, y_top=4, y_bottom=183),
            ),
        ),
    ),
)
