"""Tier 2 ReferenceChart entries for Samyang lenses (ADR-063).

Generated by `tools/mtfdigitizer/scripts/scaffold_samyang_tier2.py`.
Plot boxes for both panels (MAX, F8) auto-detected by
`samyang_plotbox.detect_samyang_plotbox`. Per-lens `image_height_mm`
comes from the scaffolder's `_IMAGE_HEIGHT_MM_BY_SLUG` table.

Do not hand-edit; re-run the scaffolder to update.

At time of generation: 18 lenses, 18 chart images (one per lens, two panels each).
"""

from __future__ import annotations

from .charts import ChartView, PlotBoxCoords, ReferenceChart


SAMYANG_TIER2_CHARTS: tuple[ReferenceChart, ...] = (
    ReferenceChart(
        slug="samyang-100mm-f2-8-ed-umc-macro",
        chart_path="docs/optical-specs/samyang-100mm-f2-8-ed-umc-macro/samyang-100mm-f2-8-ed-umc-macro-mtf.png",
        style_family="mainstream-4color-all-solid",
        apertures=("max", "stopped"),
        frequencies_lpmm=(10, 30),
        image_height_mm=21.6,
        notes=(
            "Tier 2 production entry (ADR-041, ADR-063, ADR-065). Samyang two-panel chart: max panel on top, stopped panel below, both sharing the same x-axis (image height 21.6 mm). Plot boxes auto-detected by `samyang_plotbox.detect_samyang_plotbox`; per-view aperture override emits max + stopped artifacts per pass."
        ),
        plot_box=PlotBoxCoords(x_left=31, x_right=461, y_top=43, y_bottom=463),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/samyang-100mm-f2-8-ed-umc-macro/samyang-100mm-f2-8-ed-umc-macro-mtf.png",
                plot_box=PlotBoxCoords(x_left=31, x_right=461, y_top=575, y_bottom=995),
                aperture="stopped",
            ),
        ),
    ),
    ReferenceChart(
        slug="samyang-10mm-f2-8-ed-as-ncs-cs",
        chart_path="docs/optical-specs/samyang-10mm-f2-8-ed-as-ncs-cs/samyang-10mm-f2-8-ed-as-ncs-cs-mtf.png",
        style_family="mainstream-4color-all-solid",
        apertures=("max", "stopped"),
        frequencies_lpmm=(10, 30),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041, ADR-063, ADR-065). Samyang two-panel chart: max panel on top, stopped panel below, both sharing the same x-axis (image height 14.2 mm). Plot boxes auto-detected by `samyang_plotbox.detect_samyang_plotbox`; per-view aperture override emits max + stopped artifacts per pass."
        ),
        plot_box=PlotBoxCoords(x_left=31, x_right=461, y_top=43, y_bottom=463),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/samyang-10mm-f2-8-ed-as-ncs-cs/samyang-10mm-f2-8-ed-as-ncs-cs-mtf.png",
                plot_box=PlotBoxCoords(x_left=31, x_right=461, y_top=575, y_bottom=995),
                aperture="stopped",
            ),
        ),
    ),
    ReferenceChart(
        slug="samyang-12mm-f2-0-ncs-cs",
        chart_path="docs/optical-specs/samyang-12mm-f2-0-ncs-cs/samyang-12mm-f2-0-ncs-cs-mtf.png",
        style_family="mainstream-4color-all-solid",
        apertures=("max", "stopped"),
        frequencies_lpmm=(10, 30),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041, ADR-063, ADR-065). Samyang two-panel chart: max panel on top, stopped panel below, both sharing the same x-axis (image height 14.2 mm). Plot boxes auto-detected by `samyang_plotbox.detect_samyang_plotbox`; per-view aperture override emits max + stopped artifacts per pass."
        ),
        plot_box=PlotBoxCoords(x_left=31, x_right=461, y_top=43, y_bottom=463),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/samyang-12mm-f2-0-ncs-cs/samyang-12mm-f2-0-ncs-cs-mtf.png",
                plot_box=PlotBoxCoords(x_left=31, x_right=461, y_top=575, y_bottom=995),
                aperture="stopped",
            ),
        ),
    ),
    ReferenceChart(
        slug="samyang-12mm-f2-8-ed-as-ncs-fish-eye",
        chart_path="docs/optical-specs/samyang-12mm-f2-8-ed-as-ncs-fish-eye/samyang-12mm-f2-8-ed-as-ncs-fish-eye-mtf.png",
        style_family="mainstream-4color-all-solid",
        apertures=("max", "stopped"),
        frequencies_lpmm=(10, 30),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041, ADR-063, ADR-065). Samyang two-panel chart: max panel on top, stopped panel below, both sharing the same x-axis (image height 14.2 mm). Plot boxes auto-detected by `samyang_plotbox.detect_samyang_plotbox`; per-view aperture override emits max + stopped artifacts per pass."
        ),
        plot_box=PlotBoxCoords(x_left=31, x_right=461, y_top=43, y_bottom=463),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/samyang-12mm-f2-8-ed-as-ncs-fish-eye/samyang-12mm-f2-8-ed-as-ncs-fish-eye-mtf.png",
                plot_box=PlotBoxCoords(x_left=31, x_right=461, y_top=583, y_bottom=995),
                aperture="stopped",
            ),
        ),
    ),
    ReferenceChart(
        slug="samyang-135mm-f2-0-ed-umc",
        chart_path="docs/optical-specs/samyang-135mm-f2-0-ed-umc/samyang-135mm-f2-0-ed-umc-mtf.png",
        style_family="mainstream-4color-all-solid",
        apertures=("max", "stopped"),
        frequencies_lpmm=(10, 30),
        image_height_mm=21.6,
        notes=(
            "Tier 2 production entry (ADR-041, ADR-063, ADR-065). Samyang two-panel chart: max panel on top, stopped panel below, both sharing the same x-axis (image height 21.6 mm). Plot boxes auto-detected by `samyang_plotbox.detect_samyang_plotbox`; per-view aperture override emits max + stopped artifacts per pass."
        ),
        plot_box=PlotBoxCoords(x_left=31, x_right=461, y_top=43, y_bottom=463),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/samyang-135mm-f2-0-ed-umc/samyang-135mm-f2-0-ed-umc-mtf.png",
                plot_box=PlotBoxCoords(x_left=31, x_right=461, y_top=575, y_bottom=995),
                aperture="stopped",
            ),
        ),
    ),
    ReferenceChart(
        slug="samyang-14mm-f2-8-ed-as-if-umc",
        chart_path="docs/optical-specs/samyang-14mm-f2-8-ed-as-if-umc/samyang-14mm-f2-8-ed-as-if-umc-mtf.png",
        style_family="mainstream-4color-all-solid",
        apertures=("max", "stopped"),
        frequencies_lpmm=(10, 30),
        image_height_mm=21.6,
        notes=(
            "Tier 2 production entry (ADR-041, ADR-063, ADR-065). Samyang two-panel chart: max panel on top, stopped panel below, both sharing the same x-axis (image height 21.6 mm). Plot boxes auto-detected by `samyang_plotbox.detect_samyang_plotbox`; per-view aperture override emits max + stopped artifacts per pass."
        ),
        plot_box=PlotBoxCoords(x_left=31, x_right=461, y_top=43, y_bottom=463),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/samyang-14mm-f2-8-ed-as-if-umc/samyang-14mm-f2-8-ed-as-if-umc-mtf.png",
                plot_box=PlotBoxCoords(x_left=31, x_right=461, y_top=575, y_bottom=995),
                aperture="stopped",
            ),
        ),
    ),
    ReferenceChart(
        slug="samyang-16mm-f2-0-ed-as-umc-cs",
        chart_path="docs/optical-specs/samyang-16mm-f2-0-ed-as-umc-cs/samyang-16mm-f2-0-ed-as-umc-cs-mtf.png",
        style_family="mainstream-4color-all-solid",
        apertures=("max", "stopped"),
        frequencies_lpmm=(10, 30),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041, ADR-063, ADR-065). Samyang two-panel chart: max panel on top, stopped panel below, both sharing the same x-axis (image height 14.2 mm). Plot boxes auto-detected by `samyang_plotbox.detect_samyang_plotbox`; per-view aperture override emits max + stopped artifacts per pass."
        ),
        plot_box=PlotBoxCoords(x_left=31, x_right=461, y_top=43, y_bottom=463),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/samyang-16mm-f2-0-ed-as-umc-cs/samyang-16mm-f2-0-ed-as-umc-cs-mtf.png",
                plot_box=PlotBoxCoords(x_left=31, x_right=461, y_top=575, y_bottom=995),
                aperture="stopped",
            ),
        ),
    ),
    ReferenceChart(
        slug="samyang-20mm-f1-8-ed-as-umc",
        chart_path="docs/optical-specs/samyang-20mm-f1-8-ed-as-umc/samyang-20mm-f1-8-ed-as-umc-mtf.png",
        style_family="mainstream-4color-all-solid",
        apertures=("max", "stopped"),
        frequencies_lpmm=(10, 30),
        image_height_mm=21.6,
        notes=(
            "Tier 2 production entry (ADR-041, ADR-063, ADR-065). Samyang two-panel chart: max panel on top, stopped panel below, both sharing the same x-axis (image height 21.6 mm). Plot boxes auto-detected by `samyang_plotbox.detect_samyang_plotbox`; per-view aperture override emits max + stopped artifacts per pass."
        ),
        plot_box=PlotBoxCoords(x_left=31, x_right=461, y_top=43, y_bottom=463),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/samyang-20mm-f1-8-ed-as-umc/samyang-20mm-f1-8-ed-as-umc-mtf.png",
                plot_box=PlotBoxCoords(x_left=31, x_right=461, y_top=575, y_bottom=995),
                aperture="stopped",
            ),
        ),
    ),
    ReferenceChart(
        slug="samyang-21mm-f1-4-ed-as-umc-cs",
        chart_path="docs/optical-specs/samyang-21mm-f1-4-ed-as-umc-cs/samyang-21mm-f1-4-ed-as-umc-cs-mtf.png",
        style_family="mainstream-4color-all-solid",
        apertures=("max", "stopped"),
        frequencies_lpmm=(10, 30),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041, ADR-063, ADR-065). Samyang two-panel chart: max panel on top, stopped panel below, both sharing the same x-axis (image height 14.2 mm). Plot boxes auto-detected by `samyang_plotbox.detect_samyang_plotbox`; per-view aperture override emits max + stopped artifacts per pass."
        ),
        plot_box=PlotBoxCoords(x_left=31, x_right=461, y_top=43, y_bottom=463),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/samyang-21mm-f1-4-ed-as-umc-cs/samyang-21mm-f1-4-ed-as-umc-cs-mtf.png",
                plot_box=PlotBoxCoords(x_left=31, x_right=461, y_top=575, y_bottom=995),
                aperture="stopped",
            ),
        ),
    ),
    ReferenceChart(
        slug="samyang-35mm-f1-2-ed-as-umc-cs",
        chart_path="docs/optical-specs/samyang-35mm-f1-2-ed-as-umc-cs/samyang-35mm-f1-2-ed-as-umc-cs-mtf.png",
        style_family="mainstream-4color-all-solid",
        apertures=("max", "stopped"),
        frequencies_lpmm=(10, 30),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041, ADR-063, ADR-065). Samyang two-panel chart: max panel on top, stopped panel below, both sharing the same x-axis (image height 14.2 mm). Plot boxes auto-detected by `samyang_plotbox.detect_samyang_plotbox`; per-view aperture override emits max + stopped artifacts per pass."
        ),
        plot_box=PlotBoxCoords(x_left=31, x_right=461, y_top=43, y_bottom=463),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/samyang-35mm-f1-2-ed-as-umc-cs/samyang-35mm-f1-2-ed-as-umc-cs-mtf.png",
                plot_box=PlotBoxCoords(x_left=31, x_right=461, y_top=575, y_bottom=995),
                aperture="stopped",
            ),
        ),
    ),
    ReferenceChart(
        slug="samyang-35mm-f1-4-as-umc",
        chart_path="docs/optical-specs/samyang-35mm-f1-4-as-umc/samyang-35mm-f1-4-as-umc-mtf.png",
        style_family="mainstream-4color-all-solid",
        apertures=("max", "stopped"),
        frequencies_lpmm=(10, 30),
        image_height_mm=21.6,
        notes=(
            "Tier 2 production entry (ADR-041, ADR-063, ADR-065). Samyang two-panel chart: max panel on top, stopped panel below, both sharing the same x-axis (image height 21.6 mm). Plot boxes auto-detected by `samyang_plotbox.detect_samyang_plotbox`; per-view aperture override emits max + stopped artifacts per pass."
        ),
        plot_box=PlotBoxCoords(x_left=31, x_right=461, y_top=43, y_bottom=463),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/samyang-35mm-f1-4-as-umc/samyang-35mm-f1-4-as-umc-mtf.png",
                plot_box=PlotBoxCoords(x_left=31, x_right=461, y_top=575, y_bottom=995),
                aperture="stopped",
            ),
        ),
    ),
    ReferenceChart(
        slug="samyang-50mm-f1-2-as-umc-cs",
        chart_path="docs/optical-specs/samyang-50mm-f1-2-as-umc-cs/samyang-50mm-f1-2-as-umc-cs-mtf.png",
        style_family="mainstream-4color-all-solid",
        apertures=("max", "stopped"),
        frequencies_lpmm=(10, 30),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041, ADR-063, ADR-065). Samyang two-panel chart: max panel on top, stopped panel below, both sharing the same x-axis (image height 14.2 mm). Plot boxes auto-detected by `samyang_plotbox.detect_samyang_plotbox`; per-view aperture override emits max + stopped artifacts per pass."
        ),
        plot_box=PlotBoxCoords(x_left=31, x_right=461, y_top=43, y_bottom=463),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/samyang-50mm-f1-2-as-umc-cs/samyang-50mm-f1-2-as-umc-cs-mtf.png",
                plot_box=PlotBoxCoords(x_left=31, x_right=461, y_top=575, y_bottom=995),
                aperture="stopped",
            ),
        ),
    ),
    ReferenceChart(
        slug="samyang-50mm-f1-4-as-umc",
        chart_path="docs/optical-specs/samyang-50mm-f1-4-as-umc/samyang-50mm-f1-4-as-umc-mtf.png",
        style_family="mainstream-4color-all-solid",
        apertures=("max", "stopped"),
        frequencies_lpmm=(10, 30),
        image_height_mm=21.6,
        notes=(
            "Tier 2 production entry (ADR-041, ADR-063, ADR-065). Samyang two-panel chart: max panel on top, stopped panel below, both sharing the same x-axis (image height 21.6 mm). Plot boxes auto-detected by `samyang_plotbox.detect_samyang_plotbox`; per-view aperture override emits max + stopped artifacts per pass."
        ),
        plot_box=PlotBoxCoords(x_left=36, x_right=466, y_top=43, y_bottom=463),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/samyang-50mm-f1-4-as-umc/samyang-50mm-f1-4-as-umc-mtf.png",
                plot_box=PlotBoxCoords(x_left=36, x_right=466, y_top=575, y_bottom=995),
                aperture="stopped",
            ),
        ),
    ),
    ReferenceChart(
        slug="samyang-8mm-f2-8-ed-as-if-umc-fisheye",
        chart_path="docs/optical-specs/samyang-8mm-f2-8-ed-as-if-umc-fisheye/samyang-8mm-f2-8-ed-as-if-umc-fisheye-mtf.png",
        style_family="mainstream-4color-all-solid",
        apertures=("max", "stopped"),
        frequencies_lpmm=(10, 30),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041, ADR-063, ADR-065). Samyang two-panel chart: max panel on top, stopped panel below, both sharing the same x-axis (image height 14.2 mm). Plot boxes auto-detected by `samyang_plotbox.detect_samyang_plotbox`; per-view aperture override emits max + stopped artifacts per pass."
        ),
        plot_box=PlotBoxCoords(x_left=31, x_right=461, y_top=43, y_bottom=463),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/samyang-8mm-f2-8-ed-as-if-umc-fisheye/samyang-8mm-f2-8-ed-as-if-umc-fisheye-mtf.png",
                plot_box=PlotBoxCoords(x_left=31, x_right=461, y_top=575, y_bottom=995),
                aperture="stopped",
            ),
        ),
    ),
    ReferenceChart(
        slug="samyang-8mm-f3-5-aspherical-if-mc-fish-eye",
        chart_path="docs/optical-specs/samyang-8mm-f3-5-aspherical-if-mc-fish-eye/samyang-8mm-f3-5-aspherical-if-mc-fish-eye-mtf.png",
        style_family="mainstream-4color-all-solid",
        apertures=("max", "stopped"),
        frequencies_lpmm=(10, 30),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041, ADR-063, ADR-065). Samyang two-panel chart: max panel on top, stopped panel below, both sharing the same x-axis (image height 14.2 mm). Plot boxes auto-detected by `samyang_plotbox.detect_samyang_plotbox`; per-view aperture override emits max + stopped artifacts per pass."
        ),
        plot_box=PlotBoxCoords(x_left=31, x_right=461, y_top=43, y_bottom=463),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/samyang-8mm-f3-5-aspherical-if-mc-fish-eye/samyang-8mm-f3-5-aspherical-if-mc-fish-eye-mtf.png",
                plot_box=PlotBoxCoords(x_left=31, x_right=461, y_top=575, y_bottom=995),
                aperture="stopped",
            ),
        ),
    ),
    ReferenceChart(
        slug="samyang-af-12mm-f2-0",
        chart_path="docs/optical-specs/samyang-af-12mm-f2-0/samyang-af-12mm-f2-0-mtf.png",
        style_family="mainstream-4color-all-solid",
        apertures=("max", "stopped"),
        frequencies_lpmm=(10, 30),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041, ADR-063, ADR-065). Samyang two-panel chart: max panel on top, stopped panel below, both sharing the same x-axis (image height 14.2 mm). Plot boxes auto-detected by `samyang_plotbox.detect_samyang_plotbox`; per-view aperture override emits max + stopped artifacts per pass."
        ),
        plot_box=PlotBoxCoords(x_left=31, x_right=432, y_top=43, y_bottom=463),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/samyang-af-12mm-f2-0/samyang-af-12mm-f2-0-mtf.png",
                plot_box=PlotBoxCoords(x_left=31, x_right=432, y_top=570, y_bottom=990),
                aperture="stopped",
            ),
        ),
    ),
    ReferenceChart(
        slug="samyang-af-75mm-f1-8",
        chart_path="docs/optical-specs/samyang-af-75mm-f1-8/samyang-af-75mm-f1-8-mtf.png",
        style_family="mainstream-4color-all-solid",
        apertures=("max", "stopped"),
        frequencies_lpmm=(10, 30),
        image_height_mm=14.2,
        notes=(
            "Tier 2 production entry (ADR-041, ADR-063, ADR-065). Samyang two-panel chart: max panel on top, stopped panel below, both sharing the same x-axis (image height 14.2 mm). Plot boxes auto-detected by `samyang_plotbox.detect_samyang_plotbox`; per-view aperture override emits max + stopped artifacts per pass."
        ),
        plot_box=PlotBoxCoords(x_left=67, x_right=477, y_top=43, y_bottom=463),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/samyang-af-75mm-f1-8/samyang-af-75mm-f1-8-mtf.png",
                plot_box=PlotBoxCoords(x_left=67, x_right=477, y_top=570, y_bottom=990),
                aperture="stopped",
            ),
        ),
    ),
    ReferenceChart(
        slug="samyang-tiltshift-24mm-f3-5-ed-as-umc",
        chart_path="docs/optical-specs/samyang-tiltshift-24mm-f3-5-ed-as-umc/samyang-tiltshift-24mm-f3-5-ed-as-umc-mtf.png",
        style_family="mainstream-4color-all-solid",
        apertures=("max", "stopped"),
        frequencies_lpmm=(10, 30),
        image_height_mm=21.6,
        notes=(
            "Tier 2 production entry (ADR-041, ADR-063, ADR-065). Samyang two-panel chart: max panel on top, stopped panel below, both sharing the same x-axis (image height 21.6 mm). Plot boxes auto-detected by `samyang_plotbox.detect_samyang_plotbox`; per-view aperture override emits max + stopped artifacts per pass."
        ),
        plot_box=PlotBoxCoords(x_left=31, x_right=461, y_top=43, y_bottom=463),
        ground_truth=None,
        additional_views=(
            ChartView(
                chart_path="docs/optical-specs/samyang-tiltshift-24mm-f3-5-ed-as-umc/samyang-tiltshift-24mm-f3-5-ed-as-umc-mtf.png",
                plot_box=PlotBoxCoords(x_left=31, x_right=461, y_top=575, y_bottom=995),
                aperture="stopped",
            ),
        ),
    ),
)
