"""Tier 2 ReferenceChart entries for TTartisan lenses (ADR-044).

Generated by `tools/mtfdigitizer/scripts/scaffold_ttartisan_tier2.py`.
Plot box and image-height scheme auto-detected by
`ttartisan_plotbox.detect_ttartisan_plotbox`. Per-lens aperture
pair (max, stopped) eye-read from each chart's legend and held
in `_APERTURES_BY_SLUG` in the scaffolder.

Do not hand-edit; re-run the scaffolder to update.

At time of generation: 16 lenses, 16 chart images (one per lens).
"""

from __future__ import annotations

from .charts import PlotBoxCoords, ReferenceChart


TTARTISAN_TIER2_CHARTS: tuple[ReferenceChart, ...] = (
    ReferenceChart(
        slug="ttartisan-100mm-f2-8-macro-2x-gfx",
        chart_path="docs/optical-specs/ttartisan-100mm-f2-8-macro-2x-gfx/ttartisan-100mm-f2-8-macro-2x-gfx-mtf.png",
        style_family="ttartisan-4color-dual-aperture",
        apertures=("f/2.8", "f/8"),
        frequencies_lpmm=(10, 30),
        image_height_mm=20.5,
        notes=(
            "Tier 2 production entry (ADR-041, ADR-044). TTartisan publishes this chart as the standard 800x600 dual-aperture template; the scaffolder classified it as 'gfx-or-ff' (image height 20.5 mm). Max aperture f/2.8, stopped aperture f/8 — eye-read from the chart legend per `scaffold_ttartisan_tier2._APERTURES_BY_SLUG`."
        ),
        plot_box=PlotBoxCoords(x_left=93, x_right=609, y_top=117, y_bottom=459),
        ground_truth=None,
    ),
    ReferenceChart(
        slug="ttartisan-100mm-f2-8-macro-2x-tilt-shift",
        chart_path="docs/optical-specs/ttartisan-100mm-f2-8-macro-2x-tilt-shift/ttartisan-100mm-f2-8-macro-2x-tilt-shift-mtf.png",
        style_family="ttartisan-4color-dual-aperture",
        apertures=("f/2.8", "f/8"),
        frequencies_lpmm=(10, 30),
        image_height_mm=20.5,
        notes=(
            "Tier 2 production entry (ADR-041, ADR-044). TTartisan publishes this chart as the standard 800x600 dual-aperture template; the scaffolder classified it as 'gfx-or-ff' (image height 20.5 mm). Max aperture f/2.8, stopped aperture f/8 — eye-read from the chart legend per `scaffold_ttartisan_tier2._APERTURES_BY_SLUG`."
        ),
        plot_box=PlotBoxCoords(x_left=93, x_right=609, y_top=117, y_bottom=459),
        ground_truth=None,
    ),
    ReferenceChart(
        slug="ttartisan-11mm-f2-8-fisheye-gfx",
        chart_path="docs/optical-specs/ttartisan-11mm-f2-8-fisheye-gfx/ttartisan-11mm-f2-8-fisheye-gfx-mtf.png",
        style_family="ttartisan-4color-dual-aperture",
        apertures=("f/2.8", "f/5.6"),
        frequencies_lpmm=(10, 30),
        image_height_mm=20.5,
        notes=(
            "Tier 2 production entry (ADR-041, ADR-044). TTartisan publishes this chart as the standard 800x600 dual-aperture template; the scaffolder classified it as 'gfx-or-ff' (image height 20.5 mm). Max aperture f/2.8, stopped aperture f/5.6 — eye-read from the chart legend per `scaffold_ttartisan_tier2._APERTURES_BY_SLUG`."
        ),
        plot_box=PlotBoxCoords(x_left=93, x_right=609, y_top=117, y_bottom=459),
        ground_truth=None,
    ),
    ReferenceChart(
        slug="ttartisan-23mm-f1-4",
        chart_path="docs/optical-specs/ttartisan-23mm-f1-4/ttartisan-23mm-f1-4-mtf.png",
        style_family="ttartisan-4color-dual-aperture",
        apertures=("f/1.4", "f/5.6"),
        frequencies_lpmm=(10, 30),
        image_height_mm=20.5,
        notes=(
            "Tier 2 production entry (ADR-041, ADR-044). TTartisan publishes this chart as the standard 800x600 dual-aperture template; the scaffolder classified it as 'gfx-or-ff' (image height 20.5 mm). Max aperture f/1.4, stopped aperture f/5.6 — eye-read from the chart legend per `scaffold_ttartisan_tier2._APERTURES_BY_SLUG`."
        ),
        plot_box=PlotBoxCoords(x_left=93, x_right=609, y_top=117, y_bottom=459),
        ground_truth=None,
    ),
    ReferenceChart(
        slug="ttartisan-25mm-f2-0",
        chart_path="docs/optical-specs/ttartisan-25mm-f2-0/ttartisan-25mm-f2-0-mtf.png",
        style_family="ttartisan-4color-dual-aperture",
        apertures=("f/2", "f/8"),
        frequencies_lpmm=(10, 30),
        image_height_mm=14.0,
        notes=(
            "Tier 2 production entry (ADR-041, ADR-044). TTartisan publishes this chart as the standard 800x600 dual-aperture template; the scaffolder classified it as 'aps-c' (image height 14.0 mm). Max aperture f/2, stopped aperture f/8 — eye-read from the chart legend per `scaffold_ttartisan_tier2._APERTURES_BY_SLUG`."
        ),
        plot_box=PlotBoxCoords(x_left=87, x_right=607, y_top=116, y_bottom=461),
        ground_truth=None,
    ),
    ReferenceChart(
        slug="ttartisan-35mm-f1-4",
        chart_path="docs/optical-specs/ttartisan-35mm-f1-4/ttartisan-35mm-f1-4-mtf.png",
        style_family="ttartisan-4color-dual-aperture",
        apertures=("f/1.4", "f/8"),
        frequencies_lpmm=(10, 30),
        image_height_mm=14.0,
        notes=(
            "Tier 2 production entry (ADR-041, ADR-044). TTartisan publishes this chart as the standard 800x600 dual-aperture template; the scaffolder classified it as 'aps-c' (image height 14.0 mm). Max aperture f/1.4, stopped aperture f/8 — eye-read from the chart legend per `scaffold_ttartisan_tier2._APERTURES_BY_SLUG`."
        ),
        plot_box=PlotBoxCoords(x_left=87, x_right=607, y_top=116, y_bottom=461),
        ground_truth=None,
    ),
    ReferenceChart(
        slug="ttartisan-40mm-f2-8-macro",
        chart_path="docs/optical-specs/ttartisan-40mm-f2-8-macro/ttartisan-40mm-f2-8-macro-mtf.png",
        style_family="ttartisan-4color-dual-aperture",
        apertures=("f/2.8", "f/8"),
        frequencies_lpmm=(10, 30),
        image_height_mm=14.0,
        notes=(
            "Tier 2 production entry (ADR-041, ADR-044). TTartisan publishes this chart as the standard 800x600 dual-aperture template; the scaffolder classified it as 'aps-c' (image height 14.0 mm). Max aperture f/2.8, stopped aperture f/8 — eye-read from the chart legend per `scaffold_ttartisan_tier2._APERTURES_BY_SLUG`."
        ),
        plot_box=PlotBoxCoords(x_left=87, x_right=607, y_top=116, y_bottom=461),
        ground_truth=None,
    ),
    ReferenceChart(
        slug="ttartisan-500mm-f6-3",
        chart_path="docs/optical-specs/ttartisan-500mm-f6-3/ttartisan-500mm-f6-3-mtf.png",
        style_family="ttartisan-4color-dual-aperture",
        apertures=("f/6.3", "f/11"),
        frequencies_lpmm=(10, 30),
        image_height_mm=20.5,
        notes=(
            "Tier 2 production entry (ADR-041, ADR-044). TTartisan publishes this chart as the standard 800x600 dual-aperture template; the scaffolder classified it as 'gfx-or-ff' (image height 20.5 mm). Max aperture f/6.3, stopped aperture f/11 — eye-read from the chart legend per `scaffold_ttartisan_tier2._APERTURES_BY_SLUG`."
        ),
        plot_box=PlotBoxCoords(x_left=93, x_right=609, y_top=117, y_bottom=459),
        ground_truth=None,
    ),
    ReferenceChart(
        slug="ttartisan-500mm-f6-3-gfx",
        chart_path="docs/optical-specs/ttartisan-500mm-f6-3-gfx/ttartisan-500mm-f6-3-gfx-mtf.png",
        style_family="ttartisan-4color-dual-aperture",
        apertures=("f/6.3", "f/11"),
        frequencies_lpmm=(10, 30),
        image_height_mm=20.5,
        notes=(
            "Tier 2 production entry (ADR-041, ADR-044). TTartisan publishes this chart as the standard 800x600 dual-aperture template; the scaffolder classified it as 'gfx-or-ff' (image height 20.5 mm). Max aperture f/6.3, stopped aperture f/11 — eye-read from the chart legend per `scaffold_ttartisan_tier2._APERTURES_BY_SLUG`."
        ),
        plot_box=PlotBoxCoords(x_left=93, x_right=609, y_top=117, y_bottom=459),
        ground_truth=None,
    ),
    ReferenceChart(
        slug="ttartisan-50mm-f2-0",
        chart_path="docs/optical-specs/ttartisan-50mm-f2-0/ttartisan-50mm-f2-0-mtf.png",
        style_family="ttartisan-4color-dual-aperture",
        apertures=("f/2", "f/8"),
        frequencies_lpmm=(10, 30),
        image_height_mm=20.5,
        notes=(
            "Tier 2 production entry (ADR-041, ADR-044). TTartisan publishes this chart as the standard 800x600 dual-aperture template; the scaffolder classified it as 'gfx-or-ff' (image height 20.5 mm). Max aperture f/2, stopped aperture f/8 — eye-read from the chart legend per `scaffold_ttartisan_tier2._APERTURES_BY_SLUG`."
        ),
        plot_box=PlotBoxCoords(x_left=93, x_right=609, y_top=117, y_bottom=459),
        ground_truth=None,
    ),
    ReferenceChart(
        slug="ttartisan-90mm-f1-25-gfx",
        chart_path="docs/optical-specs/ttartisan-90mm-f1-25-gfx/ttartisan-90mm-f1-25-gfx-mtf.png",
        style_family="ttartisan-4color-dual-aperture",
        apertures=("f/1.25", "f/5.6"),
        frequencies_lpmm=(10, 30),
        image_height_mm=20.5,
        notes=(
            "Tier 2 production entry (ADR-041, ADR-044). TTartisan publishes this chart as the standard 800x600 dual-aperture template; the scaffolder classified it as 'gfx-or-ff' (image height 20.5 mm). Max aperture f/1.25, stopped aperture f/5.6 — eye-read from the chart legend per `scaffold_ttartisan_tier2._APERTURES_BY_SLUG`."
        ),
        plot_box=PlotBoxCoords(x_left=93, x_right=609, y_top=117, y_bottom=459),
        ground_truth=None,
    ),
    ReferenceChart(
        slug="ttartisan-af-27mm-f2-8",
        chart_path="docs/optical-specs/ttartisan-af-27mm-f2-8/ttartisan-af-27mm-f2-8-mtf.png",
        style_family="ttartisan-4color-dual-aperture",
        apertures=("f/2.8", "f/8"),
        frequencies_lpmm=(10, 30),
        image_height_mm=14.0,
        notes=(
            "Tier 2 production entry (ADR-041, ADR-044). TTartisan publishes this chart as the standard 800x600 dual-aperture template; the scaffolder classified it as 'aps-c' (image height 14.0 mm). Max aperture f/2.8, stopped aperture f/8 — eye-read from the chart legend per `scaffold_ttartisan_tier2._APERTURES_BY_SLUG`."
        ),
        plot_box=PlotBoxCoords(x_left=87, x_right=607, y_top=116, y_bottom=461),
        ground_truth=None,
    ),
    ReferenceChart(
        slug="ttartisan-af-56mm-f1-8",
        chart_path="docs/optical-specs/ttartisan-af-56mm-f1-8/ttartisan-af-56mm-f1-8-mtf.png",
        style_family="ttartisan-4color-dual-aperture",
        apertures=("f/1.8", "f/5.6"),
        frequencies_lpmm=(10, 30),
        image_height_mm=14.0,
        notes=(
            "Tier 2 production entry (ADR-041, ADR-044). TTartisan publishes this chart as the standard 800x600 dual-aperture template; the scaffolder classified it as 'aps-c' (image height 14.0 mm). Max aperture f/1.8, stopped aperture f/5.6 — eye-read from the chart legend per `scaffold_ttartisan_tier2._APERTURES_BY_SLUG`."
        ),
        plot_box=PlotBoxCoords(x_left=87, x_right=607, y_top=116, y_bottom=461),
        ground_truth=None,
    ),
    ReferenceChart(
        slug="ttartisan-af-75mm-f2-0",
        chart_path="docs/optical-specs/ttartisan-af-75mm-f2-0/ttartisan-af-75mm-f2-0-mtf.png",
        style_family="ttartisan-4color-dual-aperture",
        apertures=("f/2", "f/5.6"),
        frequencies_lpmm=(10, 30),
        image_height_mm=20.5,
        notes=(
            "Tier 2 production entry (ADR-041, ADR-044). TTartisan publishes this chart as the standard 800x600 dual-aperture template; the scaffolder classified it as 'gfx-or-ff' (image height 20.5 mm). Max aperture f/2, stopped aperture f/5.6 — eye-read from the chart legend per `scaffold_ttartisan_tier2._APERTURES_BY_SLUG`."
        ),
        plot_box=PlotBoxCoords(x_left=93, x_right=609, y_top=117, y_bottom=459),
        ground_truth=None,
    ),
    ReferenceChart(
        slug="ttartisan-tilt-35mm-f1-4",
        chart_path="docs/optical-specs/ttartisan-tilt-35mm-f1-4/ttartisan-tilt-35mm-f1-4-mtf.png",
        style_family="ttartisan-4color-dual-aperture",
        apertures=("f/1.4", "f/8"),
        frequencies_lpmm=(10, 30),
        image_height_mm=14.0,
        notes=(
            "Tier 2 production entry (ADR-041, ADR-044). TTartisan publishes this chart as the standard 800x600 dual-aperture template; the scaffolder classified it as 'aps-c' (image height 14.0 mm). Max aperture f/1.4, stopped aperture f/8 — eye-read from the chart legend per `scaffold_ttartisan_tier2._APERTURES_BY_SLUG`."
        ),
        plot_box=PlotBoxCoords(x_left=87, x_right=607, y_top=116, y_bottom=461),
        ground_truth=None,
    ),
    ReferenceChart(
        slug="ttartisan-tilt-50mm-f1-4",
        chart_path="docs/optical-specs/ttartisan-tilt-50mm-f1-4/ttartisan-tilt-50mm-f1-4-mtf.png",
        style_family="ttartisan-4color-dual-aperture",
        apertures=("f/1.4", "f/8"),
        frequencies_lpmm=(10, 30),
        image_height_mm=20.5,
        notes=(
            "Tier 2 production entry (ADR-041, ADR-044). TTartisan publishes this chart as the standard 800x600 dual-aperture template; the scaffolder classified it as 'gfx-or-ff' (image height 20.5 mm). Max aperture f/1.4, stopped aperture f/8 — eye-read from the chart legend per `scaffold_ttartisan_tier2._APERTURES_BY_SLUG`."
        ),
        plot_box=PlotBoxCoords(x_left=93, x_right=609, y_top=117, y_bottom=459),
        ground_truth=None,
    ),
)
